/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.quizcreator;

import com.mycompany.quizcreator.beans.Question;
import com.mycompany.quizcreator.questiondatabase.QuestionDatabase;
import java.awt.event.KeyEvent;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author 23379
 */
public class AddQuestions extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddInternalFrame
     */
    public AddQuestions() {
        initComponents();
    }

    private static final Logger LOG = LogManager.getLogger(AddQuestions.class);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correctOptions = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        questionID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        firstOption = new javax.swing.JTextField();
        secondOption = new javax.swing.JTextField();
        thirdOption = new javax.swing.JTextField();
        fourthOption = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        firstCorrectOption = new javax.swing.JCheckBox();
        secondCorrectOption = new javax.swing.JCheckBox();
        thirdCorrectOption = new javax.swing.JCheckBox();
        fourthCorrectOption = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Add Question");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(940, 699));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Question ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Question");

        questionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionIDActionPerformed(evt);
            }
        });
        questionID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                questionIDKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Options");

        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("ADD QUESTIONS");

        correctOptions.add(firstCorrectOption);
        firstCorrectOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstCorrectOption.setText("Correct Answer");

        correctOptions.add(secondCorrectOption);
        secondCorrectOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        secondCorrectOption.setText("Correct Answer");

        correctOptions.add(thirdCorrectOption);
        thirdCorrectOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        thirdCorrectOption.setText("Correct Answer");

        correctOptions.add(fourthCorrectOption);
        fourthCorrectOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fourthCorrectOption.setText("Correct Answer");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("First Option");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Second Option");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Third Option");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Fourth Option");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("(Only Numbers Allowed)");

        question.setColumns(20);
        question.setLineWrap(true);
        question.setRows(5);
        question.setWrapStyleWord(true);
        jScrollPane1.setViewportView(question);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addGap(209, 209, 209)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(secondOption, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstOption, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdOption, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fourthOption, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstCorrectOption)
                            .addComponent(secondCorrectOption)
                            .addComponent(thirdCorrectOption)
                            .addComponent(fourthCorrectOption)))
                    .addComponent(questionID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addComponent(questionID, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(firstCorrectOption)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addComponent(secondCorrectOption)
                        .addGap(27, 27, 27)
                        .addComponent(thirdCorrectOption)
                        .addGap(27, 27, 27)
                        .addComponent(fourthCorrectOption))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(secondOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(thirdOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourthOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(cancelBtn))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if (questionID.getText().isEmpty()
                || this.question.getText().isEmpty()
                || firstOption.getText().isEmpty()
                || secondOption.getText().isEmpty()
                || thirdOption.getText().isEmpty()
                || fourthOption.getText().isEmpty()
                || correctOptions.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "One or more fields are left blank", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Question question = new Question();
            question.setQuestionID(Integer.parseInt(questionID.getText()));
            question.setQuestion(this.question.getText());
            question.setFirstOption(firstOption.getText());
            question.setSecondOption(secondOption.getText());
            question.setThirdOption(thirdOption.getText());
            question.setFourthOption(fourthOption.getText());

            if (firstCorrectOption.isSelected()) {
                question.setCorrectOption(firstOption.getText());
            } else if (secondCorrectOption.isSelected()) {
                question.setCorrectOption(secondOption.getText());
            } else if (thirdCorrectOption.isSelected()) {
                question.setCorrectOption(thirdOption.getText());
            } else if (fourthCorrectOption.isSelected()) {
                question.setCorrectOption(fourthOption.getText());
            }

            QuestionDatabase database = new QuestionDatabase();
            try {
                database.addQuestion(question);

                JOptionPane.showMessageDialog(this, "Question Addded Successfully!!", "Confirmation Message", JOptionPane.INFORMATION_MESSAGE);

                questionID.setText("");
                this.question.setText("");
                firstOption.setText("");
                secondOption.setText("");
                thirdOption.setText("");
                fourthOption.setText("");
                correctOptions.clearSelection();

            } catch (SQLIntegrityConstraintViolationException ex) {
                LOG.error(ex + "\n");
                JOptionPane.showMessageDialog(this, ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void questionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionIDActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void questionIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_questionIDKeyPressed
        // TODO add your handling code here:
        questionID.setTransferHandler(null);
        if (Character.isDigit(evt.getKeyChar()) || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE) {
            questionID.setEditable(true);
        } else {
            questionID.setEditable(false);
        }
    }//GEN-LAST:event_questionIDKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.ButtonGroup correctOptions;
    private javax.swing.JCheckBox firstCorrectOption;
    private javax.swing.JTextField firstOption;
    private javax.swing.JCheckBox fourthCorrectOption;
    private javax.swing.JTextField fourthOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea question;
    private javax.swing.JTextField questionID;
    private javax.swing.JCheckBox secondCorrectOption;
    private javax.swing.JTextField secondOption;
    private javax.swing.JCheckBox thirdCorrectOption;
    private javax.swing.JTextField thirdOption;
    // End of variables declaration//GEN-END:variables
}
