/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.quizcreator;

import com.mycompany.quizcreator.beans.Question;
import com.mycompany.quizcreator.questiondatabase.QuestionDatabase;
import javax.swing.JOptionPane;

/**
 *
 * @author 23379
 */
public class EditQuestion extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditQuestion
     */
    public EditQuestion(Question question) {
        initComponents();
        questionID.setText(String.valueOf(question.getQuestionID()));
        this.question.setText(question.getQuestion());
        firstOption.setText(question.getFirstOption());
        secondOption.setText(question.getSecondOption());
        thirdOption.setText(question.getThirdOption());
        fourthOption.setText(question.getFourthOption());

        if (question.getCorrectOption().equals(question.getFirstOption())) {
            firstCorrectOption.setSelected(true);
        } else if (question.getCorrectOption().equals(question.getSecondOption())) {
            secondCorrectOption.setSelected(true);
        } else if (question.getCorrectOption().equals(question.getThirdOption())) {
            thirdCorrectOption.setSelected(true);
        } else if (question.getCorrectOption().equals(question.getFourthOption())) {
            fourthCorrectOption.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correctOptions = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        questionID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        firstOption = new javax.swing.JTextField();
        secondOption = new javax.swing.JTextField();
        thirdOption = new javax.swing.JTextField();
        fourthOption = new javax.swing.JTextField();
        secondCorrectOption = new javax.swing.JCheckBox();
        firstCorrectOption = new javax.swing.JCheckBox();
        thirdCorrectOption = new javax.swing.JCheckBox();
        fourthCorrectOption = new javax.swing.JCheckBox();
        updateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("EDIT QUESTION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Question ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Question");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Option");

        questionID.setEditable(false);
        questionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionIDActionPerformed(evt);
            }
        });

        question.setColumns(20);
        question.setRows(5);
        jScrollPane1.setViewportView(question);

        correctOptions.add(secondCorrectOption);
        secondCorrectOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        secondCorrectOption.setText("Correct Answer");
        secondCorrectOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondCorrectOptionActionPerformed(evt);
            }
        });

        correctOptions.add(firstCorrectOption);
        firstCorrectOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstCorrectOption.setText("Correct Answer");

        correctOptions.add(thirdCorrectOption);
        thirdCorrectOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        thirdCorrectOption.setText("Correct Answer");

        correctOptions.add(fourthCorrectOption);
        fourthCorrectOption.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fourthCorrectOption.setText("Correct Answer");

        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(442, 442, 442))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(updateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addGap(285, 285, 285))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstOption, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                            .addComponent(secondOption)
                            .addComponent(thirdOption)
                            .addComponent(fourthOption))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fourthCorrectOption)
                            .addComponent(thirdCorrectOption)
                            .addComponent(secondCorrectOption)
                            .addComponent(firstCorrectOption)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(questionID)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(questionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstCorrectOption))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secondOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondCorrectOption))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thirdOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdCorrectOption))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourthOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fourthCorrectOption))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(222, 222, 222)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(cancelBtn))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionIDActionPerformed

    private void secondCorrectOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondCorrectOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondCorrectOptionActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (this.question.getText().isEmpty()
                || firstOption.getText().isEmpty()
                || secondOption.getText().isEmpty()
                || thirdOption.getText().isEmpty()
                || fourthOption.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "One or more fields are left blank", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Question question = new Question();
            question.setQuestionID(Integer.parseInt(questionID.getText()));
            question.setQuestion(this.question.getText());
            question.setFirstOption(firstOption.getText());
            question.setSecondOption(secondOption.getText());
            question.setThirdOption(thirdOption.getText());
            question.setFourthOption(fourthOption.getText());

            if (firstCorrectOption.isSelected()) {
                question.setCorrectOption(firstOption.getText());
            } else if (secondCorrectOption.isSelected()) {
                question.setCorrectOption(secondOption.getText());
            } else if (thirdCorrectOption.isSelected()) {
                question.setCorrectOption(thirdOption.getText());
            } else if (fourthCorrectOption.isSelected()) {
                question.setCorrectOption(fourthOption.getText());
            }

            QuestionDatabase database = new QuestionDatabase();
            if (database.updateQuestion(question)) {
                JOptionPane.showMessageDialog(this, "Question Updated Successfully!!", "Confirmation Message", JOptionPane.INFORMATION_MESSAGE);
                ViewPanel viewPort = new ViewPanel();
                viewPort.addDataRow(database.getQuestions(question));
                viewPort.setSize(this.getWidth(), this.getHeight());
                getParent().add(viewPort);
                this.dispose();
                viewPort.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Not able to update the data", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.ButtonGroup correctOptions;
    private javax.swing.JCheckBox firstCorrectOption;
    private javax.swing.JTextField firstOption;
    private javax.swing.JCheckBox fourthCorrectOption;
    private javax.swing.JTextField fourthOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea question;
    private javax.swing.JTextField questionID;
    private javax.swing.JCheckBox secondCorrectOption;
    private javax.swing.JTextField secondOption;
    private javax.swing.JCheckBox thirdCorrectOption;
    private javax.swing.JTextField thirdOption;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
